server:
  port: 9000
  servlet:
    context-path: /web-service

spring:
  application:
    name: WEBSERVICE
  config:
    import: optional:configserver:http://localhost:9196
  rabbitmq:
    host: ec2-3-83-204-113.compute-1.amazonaws.com
    port: 5672
    username: admin
    password: Secr3t
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: elk.log
    path: ${user.home}/desktop/new folder
