server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: optional:configserver:http://localhost:9196



management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

