spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wambugucoder/SPRING-CLOUD-CONFIGS
  rabbitmq:
    host: ec2-3-83-204-113.compute-1.amazonaws.com
    port: 5672
    username: admin
    password: Secr3t

server:
  port: 9196


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
